name: transaction_signing_gateway
description: Transaction Signing gateway
version: 0.0.1
homepage: tendermint.com
publish_to: 'none' # TODO publish it when ready

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.0.5"

dependencies:
  flutter:
    sdk: flutter
  equatable: 2.0.3
  flutter_secure_storage: 4.2.1
  encrypt: 5.0.1
  alan: 0.40.2+1
  uuid: 3.0.4
  cosmos_utils:
      path: ../cosmos_utils

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: 1.7.2
  mockito: 5.0.14

flutter: